keys:
  - &main C10D73542F9717B761424E7D77EEFB04BFD81826
  - &ge age1fehak2xwxm6gsckqadtexrvpjr77zj86ap73fzyl4jjx5nnq3dkqz3qq59
  - &zheng age1a6zgnkyal7jaduz35ml9ua09w3w2utj9wzpkcm47msv3t8l8s54qe7tyql
  - &lei age1e466lk9hrq735m799qvsje5tv74t6a63urg0cjy9y5kw92k2h48qtddd60
  - &dui age1mxy9hgmz7ja4ny9cvq6eqj9gpqlkfypke5jsurx6zk75asyw6f0sxcek63
  - &xun age1tmr3ndranyswjjtnfuvxv2mv4cn2wyqqguys85a40ruq2pgrhugqqw4459
creation_rules:
  - path_regex: (secrets\.yaml$|tfout\.json$)
    key_groups:
    - age:
      - *ge
      - *zheng
      - *lei
      - *dui
      - *xun
      pgp:
      - *main
  - path_regex: tf\.env$
    key_groups:
    - pgp:
      - *main
  - path_regex: chugou\.yaml$
    key_groups:
    - age:
      - *lei
      - *dui
      pgp:
      - *main
