[rime-pinyin-zhwiki]
src.archpkg = "rime-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict.yaml"

[proton-ge-custom]
src.github = "GloriousEggroll/proton-ge-custom"
fetch.url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$ver/$ver.tar.gz"

[yacd-meta]
src.git = "https://github.com/MetaCubeX/Yacd-meta"
src.branch = "gh-pages"
fetch.github = "MetaCubeX/Yacd-meta"

[metacubexd]
src.git = "https://github.com/MetaCubeX/metacubexd"
src.branch = "gh-pages"
fetch.github = "MetaCubeX/metacubexd"

[cape-yasnippet]
src.git = "https://github.com/elken/cape-yasnippet"
fetch.github = "elken/cape-yasnippet"
