# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cape-yasnippet = {
    pname = "cape-yasnippet";
    version = "ad8c27c2f748b410e7dd568927e99081f87b98b9";
    src = fetchFromGitHub {
      owner = "elken";
      repo = "cape-yasnippet";
      rev = "ad8c27c2f748b410e7dd568927e99081f87b98b9";
      fetchSubmodules = false;
      sha256 = "sha256-JmJljrvo9AcEVALv5GHa/XdpVLAUaww3wGmlXSAoITs=";
    };
    date = "2023-05-19";
  };
  jovian-nixos = {
    pname = "jovian-nixos";
    version = "449faaa41e55c504d2068f2a77c91a0dbc5b191d";
    src = fetchFromGitHub {
      owner = "Jovian-Experiments";
      repo = "Jovian-NixOS";
      rev = "449faaa41e55c504d2068f2a77c91a0dbc5b191d";
      fetchSubmodules = false;
      sha256 = "sha256-E4Lk1HlRSvbcflAB23U1Arul013IN34kvReQyulzFTw=";
    };
    date = "2023-06-30";
  };
  proton-ge-custom = {
    pname = "proton-ge-custom";
    version = "GE-Proton8-4";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-4/GE-Proton8-4.tar.gz";
      sha256 = "sha256-OPwmVxBGaWo51pDJcqvxvZ8qxMH8X0DwZTpwiKbdx/I=";
    };
  };
  rime-pinyin-zhwiki = {
    pname = "rime-pinyin-zhwiki";
    version = "20230605";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230605.dict.yaml";
      sha256 = "sha256-SB2TcvJb/7D3cO3NG34QecMxWMAFwwHCSr3sKHLZa3o=";
    };
  };
  yacd-meta = {
    pname = "yacd-meta";
    version = "2d0c52cecf9ee7ed8446d2fa240291ef83facbde";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "Yacd-meta";
      rev = "2d0c52cecf9ee7ed8446d2fa240291ef83facbde";
      fetchSubmodules = false;
      sha256 = "sha256-Pi1LV+DnBiFqcelPz/F6Ip2wH+GC87vE+9H4nCaWlBU=";
    };
    date = "2023-06-29";
  };
}
