# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  jovian-nixos = {
    pname = "jovian-nixos";
    version = "0586e3d1f3689ccd4c8820d2fd7775b39eb14c0d";
    src = fetchFromGitHub ({
      owner = "Jovian-Experiments";
      repo = "Jovian-NixOS";
      rev = "0586e3d1f3689ccd4c8820d2fd7775b39eb14c0d";
      fetchSubmodules = false;
      sha256 = "sha256-zcRbZ12jl6MB1UMLH6daBIrc5XVw0IskZD8b6Zps/aQ=";
    });
    date = "2023-04-09";
  };
  proton-ge-custom = {
    pname = "proton-ge-custom";
    version = "GE-Proton7-55";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton7-55/GE-Proton7-55.tar.gz";
      sha256 = "sha256-/70DtApcja+6U+Rb1lUcEyUSrW/LqRIOJfDVENDNBIU=";
    };
  };
  rime-pinyin-zhwiki = {
    pname = "rime-pinyin-zhwiki";
    version = "20230329";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230329.dict.yaml";
      sha256 = "sha256-0B02FGISHqvrBUGkERdplhrx8zo6SV9hG2qRbSUqqd0=";
    };
  };
  yacd-meta = {
    pname = "yacd-meta";
    version = "ac99093187a622df1badf63c4c26c71b97a5dc5b";
    src = fetchFromGitHub ({
      owner = "MetaCubeX";
      repo = "Yacd-meta";
      rev = "ac99093187a622df1badf63c4c26c71b97a5dc5b";
      fetchSubmodules = false;
      sha256 = "sha256-QuEph6CSxnyxCTj868gl4Y6YgsI2Afv14Jd7g1cSG2Q=";
    });
    date = "2023-04-22";
  };
}
