# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cape-yasnippet = {
    pname = "cape-yasnippet";
    version = "40654214db7a44db3a99321447632b43a10fae57";
    src = fetchFromGitHub {
      owner = "elken";
      repo = "cape-yasnippet";
      rev = "40654214db7a44db3a99321447632b43a10fae57";
      fetchSubmodules = false;
      sha256 = "sha256-w5gckpREvV4ET6+/wSgul0wPC42Xeb5B7rFmuuSh3M8=";
    };
    date = "2023-08-13";
  };
  jovian-nixos = {
    pname = "jovian-nixos";
    version = "8501772997eae3ca4be3584ad4e93d448b0224e5";
    src = fetchFromGitHub {
      owner = "sg-qwt";
      repo = "Jovian-NixOS";
      rev = "8501772997eae3ca4be3584ad4e93d448b0224e5";
      fetchSubmodules = false;
      sha256 = "sha256-+A2EQ+W9UrJqbqoqQj/wWJIEw8D1MFoiRKiKn0YrkgY=";
    };
    date = "2023-08-07";
  };
  proton-ge-custom = {
    pname = "proton-ge-custom";
    version = "GE-Proton8-4";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-4/GE-Proton8-4.tar.gz";
      sha256 = "sha256-OPwmVxBGaWo51pDJcqvxvZ8qxMH8X0DwZTpwiKbdx/I=";
    };
  };
  rime-pinyin-zhwiki = {
    pname = "rime-pinyin-zhwiki";
    version = "20230605";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230605.dict.yaml";
      sha256 = "sha256-SB2TcvJb/7D3cO3NG34QecMxWMAFwwHCSr3sKHLZa3o=";
    };
  };
  yacd-meta = {
    pname = "yacd-meta";
    version = "2d0c52cecf9ee7ed8446d2fa240291ef83facbde";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "Yacd-meta";
      rev = "2d0c52cecf9ee7ed8446d2fa240291ef83facbde";
      fetchSubmodules = false;
      sha256 = "sha256-Pi1LV+DnBiFqcelPz/F6Ip2wH+GC87vE+9H4nCaWlBU=";
    };
    date = "2023-06-29";
  };
}
