# credits to github.com/ifd3f/infra
{ git, writeText, writeScriptBin, runCommand, yq, rootPath, ... }:
let
  workflow = import (rootPath + "/config/github-ci.nix");
  workflowJSON =
    writeText "build.json" (builtins.toJSON workflow);

  workflowYAML = runCommand "build.yaml"
    {
      buildInputs = [ yq ];
      json = workflowJSON;
    } ''
    (
      echo "# !!!!!!!! AUTO-GENERATED FILE, DO NOT MODIFY !!!!!!!!"
      echo "# This file can be regenerated by the following command:"
      echo "#   $ nix run .#gen-github-ci"
      echo
      yq -y -r --yml-out-ver 1.2 '.' "$json" 
    ) > "$out"
  '';
in
writeScriptBin "gen-github-ci" ''
  set -euxo pipefail

  root=$(git rev-parse --show-toplevel)
  dest="$root/.github/workflows/build.yaml"

  echo "Updating workflow file: $dest" >&2

  cp ${workflowYAML} "$dest"
''
