# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let it87 = config.boot.kernelPackages.callPackage ./it87.nix { };
in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "acpi_enforce_resources=lax" ];
  boot.kernelModules = [ "kvm-amd" "it87" ];
  boot.extraModulePackages = [ it87 ];
  boot.extraModprobeConfig = ''
    options it87 ignore_resource_conflict=1
  '';

  fileSystems."/" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/me/.cache" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=userdata/cache" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/me/Downloads" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=userdata/downloads" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/me/.local/share/Steam" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=userdata/steam" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/nvme0n1p3";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A218-480E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6b5c6135-985d-43fd-84d0-a9212cdfe319"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

}
