jobs:
  build-nixos-configuration:
    needs:
    - check-flake-and-formatter
    - check-eval-host
    runs-on: ubuntu-latest
    steps:
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Make More Space
      run: 'echo "=== Before pruning ==="

        df -h

        sudo rm -rf /usr/share /usr/local /opt || true

        echo

        echo "=== After pruning ==="

        df -h

        '
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Set Swap Space
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 10
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Checkout
      uses: actions/checkout@v3
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Setup Attic Cache
      uses: icewind1991/attic-action@v1.1.1
      with:
        authToken: ${{ secrets.ATTIC_HELLO_TOKEN }}
        instance: https://attic.edgerunners.eu.org
        name: hello
    - if: ${{ (github.event.inputs.host == 'all') || (matrix.host == github.event.inputs.host)
        || (github.event.pull_request.head.repo.full_name == github.repository) ||
        (github.event_name == 'push') }}
      name: Build Host ${{ matrix.host }}
      run: "nix build --print-build-logs .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel\
        \ \n"
    strategy:
      fail-fast: false
      matrix:
        host:
        - dui
        - ge
        - lei
        - xun
        - zheng
  check-eval-host:
    needs: check-flake-and-formatter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Eval Host ${{ matrix.host }}
      run: 'nix eval --raw .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

        '
    strategy:
      fail-fast: false
      matrix:
        host:
        - dui
        - ge
        - lei
        - xun
        - zheng
  check-flake-and-formatter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Flake Check
      run: nix flake check --verbose --print-build-logs
name: Build
'on':
  pull_request: {}
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      host:
        default: all
        description: Host to build
        options:
        - dui
        - ge
        - lei
        - xun
        - zheng
        - all
        required: true
        type: choice
