name: "Build"
on: workflow_dispatch
jobs:
  build-nixos-configuration:
    strategy:
      matrix:
        host: [ge, dui, zheng, lei]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Make more space"
      run: "sudo rm -rf /opt /usr/local || true &"
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: nixqwt
        extraPullNames: nix-community,jovian-experiments
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true
    - name: Enable cache upload
      run: cachix watch-store nixqwt &
    - name: Build nixosConfigurations
      run: nix build --print-build-logs .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
