jobs:
  update-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - id: update
      name: Update
      run: 'nix run .#ci-update

        '
    - name: Create PR
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        body: ${{ steps.update.outputs.report }}
        branch: ci-update
        commit-message: 'auto: flake update'
        delete-branch: true
        title: Update flake.lock sources
        token: ${{ secrets.PAT }}
name: Update
'on':
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch: {}
